version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=default
      - DB_USERNAME=default
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    hostname: db
    container_name: db
    image: mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --default-authentication-plugin=mysql_native_password

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=default
      - DB_USERNAME=default
      - DB_PASSWORD=secret
    volumes:
      - .:/app
    depends_on:
      - db
